### PR TITLE
feat: replace inactive remove active from select account

### PR DESCRIPTION
**Pull request by doncicuto**
@juergrinaldi opened issue #4096 and suggested that when we're in select account:

> I'd either get rid of the label or - alternatively - change it to 'signed out' (for inactive), while active has no label at all. (see Google for example)

Acceptance Criteria

- [X] I only see the user session without the state of it in the select account screen. I'd either get rid of the label or - alternatively - change it to 'signed out' (for inactive), while active has no label at all. (see Google for example)

This PR replaces inactive with 'signed out' (I've used the suggested translations offered by Google in Gmail account picker) and removes the active label when the user has already signed in.

The following screenshot shows the proposed change:
image

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by doncicuto** [comment]
Absolutely @livio-a, I've added the if also to user select in console

Captura desde 2023-09-03 13-04-55

Active is no longer shown.

**Review by livio-a — APPROVED** [review]

**Comment by livio-a** [comment]
> 
> Active is no longer shown.

perfect 👌

**Comment by livio-a** [comment]
FYI @doncicuto: we seem to have an issue with the latest version of the cockroach test binary, that's why tests currently fail
we're investigating it and will merge this PR as soon as it's resolved

**Comment by doncicuto** [comment]
Thanks @livio-a, if you need me to do any changes or rerun tests locally let me know

**Comment by livio-a** [comment]
> Thanks @livio-a, if you need me to do any changes or rerun tests locally let me know

we got it sorted out. there was a wrong statement in our tests, which was fixed in the latest release of CRDB
nothing to do on your end 😃

**Pull request merged**
