### PR TITLE
docs: Update cockroach to v23.1.11

### PR DESCRIPTION
**Pull request by epvanhouten**
Sample docker-compose does not work until cockroach is updated to v23.1.11. 

https://discord.com/channels/927474939156643850/1166399185021567106

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by epvanhouten** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated (UTC)
> **docs**	✅ Ready ([Inspect](https://vercel.com/zitadel/docs/BogqumH9A1zoj72eqdtuQZhyQbKh))	[Visit Preview](https://vercel.live/open-feedback/docs-git-fork-epvanhouten-patch-1-zitadel.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)	💬 [**Add feedback**](https://vercel.live/open-feedback/docs-git-fork-epvanhouten-patch-1-zitadel.vercel.app?via=pr-comment-feedback-link)	Oct 24, 2023 5:17pm

Verified that yaml is rendering as expected at [relevant page](https://docs-git-fork-epvanhouten-patch-1-zitadel.vercel.app/docs/self-hosting/deploy/compose).

**Comment by eliobischof** [comment]
Thanks for the fix @epvanhouten :rocket: 

Not sure why, but I can't check out your PR branch.
Would you mind updating following occurences, too?
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml#L45
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/macos.mdx#L14
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/linux.mdx#L15
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/macos.mdx#L14
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/manage/configure/docker-compose.yaml#L22
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/manage/configure/docker-compose.yaml#L39

**Review by eliobischof — CHANGES_REQUESTED** [review]
Thanks for the fix @epvanhouten :rocket: 

Not sure why, but I can't check out your PR branch.
Would you mind updating following occurences, too?
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml#L45
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/macos.mdx#L14
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/linux.mdx#L15
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/deploy/macos.mdx#L14
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/manage/configure/docker-compose.yaml#L22
- https://github.com/zitadel/zitadel/blob/1fafefc2c1f89b7f1aefee4f5454cf0217218383/docs/docs/self-hosting/manage/configure/docker-compose.yaml#L39

**Comment by eliobischof** [comment]
Closing this PR in favor of https://github.com/zitadel/zitadel/pull/6803

**Pull request closed without merging**
