### PR TITLE
feat: Apply OCI source label to Docker image

### PR DESCRIPTION
**Pull request by meyfa**
This patch adds the `org.opencontainers.image.source` label to the Zitadel Docker image. This label is used by dependency update tools like Dependabot and Renovate to look up release notes for Docker image updates.

For Dependabot, see: https://github.blog/changelog/2023-04-13-dependabot-now-supports-fetching-release-notes-and-changelogs-for-docker-images/

> To enable support, add the org.opencontainers.image.source label to the Dockerfile with the URL of the source repository.

For Renovate, see: https://github.com/renovatebot/renovate/tree/main/lib/modules/datasource/docker

> If you maintain a Docker image and want Renovate to find your changelogs, add a org.opencontainers.image.source field to your Dockerfile. The link must point to your GitHub or GitLab repository.

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by meyfa** [comment]
Since there were a few multi-stage Dockerfiles in this repository, I'm not completely sure I added the label in the right place. It needs to be set on the image that gets pushed to `ghcr.io/zitadel/zitadel`.

**Comment by livio-a** [comment]
@stebenz can you please make sure this doesn't get lost when changing to the new pipeline

**Comment by eliobischof** [comment]
We appreciate your contribution @meyfa :tada: 

We'd like to say thank you by sending you some ZITADEL swag. If you like that, please send us a mail to hi@zitadel.com. We will send you a form about the shirt size, for example.

**Comment by meyfa** [comment]
@eliobischof Thanks for the approval! There are some build failures in CI, but those seem unrelated 🤔

**Comment by eliobischof** [comment]
> @eliobischof Thanks for the approval! There are some build failures in CI, but those seem unrelated 🤔 

Yeah, we have some flakiness there. I restarted it.

A big pipeline improvement is coming these days.

**Pull request merged**
