### PR TITLE
fix: introduce measures to avoid bots crawling and indexing activities

### LINKED ISSUE #5632: [Bug]: Missing robots.txt when using custom domain (cname)
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

We have configured a CNAME for our production environment. Unfortunately due to missing robots.txt, google is indexing our login page, which should not be the case. Attached you will find a screenshot of the google search result.

### To reproduce

1. Create an environment with CNAME configured
2. Integrate it with a frontend application
3. Google is indexing your page + login page

### Screenshots

image

### Expected behavior

Search engines should not be permitted to index the login page. This can be achieved by configuring the robots.txt file or sending the `X-Robots-Tag: noindex` header.

### Version

Cloud

### Operating System

irrelevant

### Relevant Configuration

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by doncicuto**
Add robots.txt, robots meta tag and X-Robots-Tag to avoid bots crawling and indexing activities for a Zitadel instance

Acceptance Criteria

- [X] We don't want bots to crawl Instance URLs, using robots.txt
- [X] We don't want bots that visit links to the Console or Login pages to index content from it, using meta tag robots set to none -> none equals noindex, nofollow
- [X] Also we don't want REST endpoints to be indexed, using "X-Robots-Tag: none"

Here are some screenshots:

HTML source code
meta_robots_none_2
meta_robots_none

API Response Headers
x_robots_tag

Robots.txt found
robots_txt

```[tasklist]

Closes #5632 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.
```

### CODE REVIEW

**Comment by hifabienne** [comment]
Thanks @doncicuto 
We are currently finishing up the current sprint and will then have a look at it.

**Comment by hifabienne** [comment]
> IMHO we can disallow robots on our login page, but disabling it in our console would also make our other meta tags unnecessary which are used to render a preview in chats / social media or doesn't it? 🤔

Who do you ask this? 😃

**Comment by peintnermax** [comment]
The PR and console changes look good to me. Maybe @adlerhurst or @livio-a can review the golang code

**Comment by livio-a** [comment]
> The PR and console changes look good to me. Maybe @adlerhurst or @livio-a can review the golang code

i'll try check in the afternoon or at latest tomorrow

**Review by adlerhurst — CHANGES_REQUESTED** [review]
please add the handler as well to the grpc-web handler here: https://github.com/doncicuto/zitadel/blob/6068796a436fba5699e39038d3c8922d27fb5437/internal/api/api.go#L176

**Comment by doncicuto** [comment]
Hi @adlerhurst, I've added the x-robots-tag to grpcwebserver as requested

grpcweb_x_robots_tag

**Review by adlerhurst — DISMISSED** [review]

**Comment by adlerhurst** [comment]
hi @doncicuto 

Thanks for your contribution. 🙏🏻
Looks good to me.

**Review by adlerhurst — APPROVED** [review]

**Pull request merged**
