### PR TITLE
fix(console): display granted org name in authorizations and show user information

### LINKED ISSUE #4531: Display of external users in authorizations is misleading
Screenshot 2022-10-10 at 15 37 19

Following scenario
- I have two organizations Demo-Vendor and Demo-Customer
- Demo-Vendor has a user "Max Vendor"
- On Demo-Customer, I create an authorization for "Max Vendor" (external user grant)

I have the following issues how this is displayed/handled in the table: 
- I can only see from my - specific user name - that the user belongs to Demo-Vendor
- The title "Organization" refers here to the authorization context, but could be misunderstood as the user-context (authorization lives in Demo-Customer, but the user lives in Demo-Vendor)
- I have no way of displaying the loginname or information about the user's organization (click opens the authorization)
- When I click on "Show user Max Vendor", then I get an Error

**Acceptance criteria**
- [ ] ...
- [ ] ...

### PR DESCRIPTION
**Pull request by doncicuto**
In this PR I deal with issues #4531 and #6141.

I've reproduced the issues reported by @mffap:

- Authorizations table shows the current organization name but not the name associated to the granted user. I've modified the backend code so information from the organization which the user is a member of is sent in the response (UserGrant) named as Granted Org. The granted organization name is shown instead of the organization name which the authorization belongs to.
- The "Show user XXXXXX" button now runs fine. The issue was that if we want to visit the user information page we must first change the console's active organization to the one associated with the user. So now we first change the org (thanks to the granted org info that goes in the backend's response) and then we navigate to the user's page.

The following video shows the fixed behaviour:

https://github.com/zitadel/zitadel/assets/30386061/1ff3ab0a-e328-4c72-a059-e938752d77ff

Closes #4531 and #6141 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by peintnermax** [comment]
@doncicuto thx a lot for this contribution. This helps a lot and improves the behaviour a lot for instance owners or if your currently logged in user has the permission to view the user. However we have to check whether the user has an org with membership before we switch org context.
I'd suggest we fetch the orgs again and check whether the id is available..
`const orgs = (await this.listMyProjectOrgs(10, 0)).resultList` would do that job or do you have a better idea? at best we load the permissions afterwards too to ensure the `user.grant:[id]` can be read but in my opinion we can let the user run into that error 🤔
Screenshot 2024-01-15 at 15 13 02

**Comment by doncicuto** [comment]
As always thanks @peintnermax for your review. I'll have a look at your suggestions as I missed that check. Also I'll try to fix the conflicts. Give me a couple of days as I'm having heavy problema at work.

**Comment by peintnermax** [comment]
> As always thanks @peintnermax for your review. I'll have a look at your suggestions as I missed that check. Also I'll try to fix the conflicts. Give me a couple of days as I'm having heavy problema at work.

no worries. thx a lot for your work.. just ping me if you need help 👍

**Comment by doncicuto** [comment]
Hi @peintnermax I've added the logic to check if user has a membership before changing the org. If the user has no membership I show a toast like this (with translations):

image

Let me know if you want me to change anything for better UX.  Also I've fixed the conflicts with main for upcoming backend review.

Thanks!

**Comment by peintnermax** [comment]
> Hi @peintnermax I've added the logic to check if user has a membership before changing the org. If the user has no membership I show a toast like this (with translations):
> 
> image
> 
> Let me know if you want me to change anything for better UX. Also I've fixed the conflicts with main for upcoming backend review.
> 
> Thanks!

Amazing.. thx a lot @doncicuto 😎

**Review by peintnermax — APPROVED** [review]

**Review by stebenz — APPROVED** [review]

**Pull request merged**
