### PR TITLE
fix: verify domain revamped

### LINKED ISSUE #6549: [Bug]: Unclear instructions what to do with DNS TOKEN
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

_No response_

### Describe the problem caused by this bug

When I create a DNS token for verification, then I get he following modal: 

Screenshot 2023-09-13 at 16 50 15

Only the first part can be copied to the clipboard. It is unclear what to do with the second part `_zitadel-challenge.foobar.com`.

### To reproduce

1. Create an organization domain
2. Verify the domain with DNS challenge

### Screenshots

_No response_

### Expected behavior

Provide labels for the two values and guidance how to construct the value. Some domain registrars might require different configuration. If we can't provide this info on the modal, then we should point to a documentation that explains it for the major registrars.

### Operating System

_No response_

### Relevant Configuration

_No response_

### Additional Context

The verify button should be somewhere else according to the text. I would suggest to move it to the very bottom (not to the side of the token) and change the description.

### PR DESCRIPTION
**Pull request by doncicuto**
In #6549, @mffap commented that instructions about domain verification using DNS tokens were not clear.

This PR proposes a revamped dialog for domain verification.

Here's the dialog window when a new verification is triggered:

console_verify_domain

If user selects the DNS method here's the proposed dialog, where both the host name for the record and its expected value can be copied.

Captura desde 2023-11-23 21-20-59

If user selects HTTP method here's the proposed dialog, where the expected url can be copied and we have the current download file button. 

Captura desde 2023-11-23 21-21-08

If the user skips the verification, she can resume the verification or reset the process:

Captura desde 2023-11-23 21-21-29

This PR also adds some links to popular DNS providers documentation about how to add a TXT record to a domain.

Closes #6549 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [X] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Review by eliobischof — COMMENTED** [review]
Once again a fantastic job @doncicuto :tada: 
Great work, thank you! :pray: 

Maybe we can link to https://zitadel.com/docs/guides/manage/console/organizations#verify-your-domain-name directly from within the dialog to guide the user even better?

**Comment by doncicuto** [comment]
Hi @eliobischof. How about this:

image

**Comment by eliobischof** [comment]
> Hi @eliobischof. How about this:
> 
> image

Maybe just an icon next to the titles, like at *Verified domains*? 
image

**Comment by doncicuto** [comment]
Ok @eliobischof after struggling with css I got this:

image

**Pull request merged**
