### PR TITLE
docs(self-hosted): Generate docs for env variables

### LINKED ISSUE #4976: Docs: Configuration options vs environment variables
As Dev I want to understand how to configure zitadel for testing/dev and production.

Background: 
I was not able to fully understand how our system can be configured via code/variables for a dev and prod scenario, based on our documentation.

Observations:
 - [Docker compose](https://zitadel.com/docs/self-hosting/deploy/compose) uses env variables
 - [LB example](https://zitadel.com/docs/self-hosting/deploy/loadbalancing-example) uses config files
- Both options are explained in the [Configuration Options](https://zitadel.com/docs/self-hosting/manage/configure) page
- The actual config parameters are in [here](https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml) and [here](https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml)
- Some relevant configuration parameters are missing a comment (eg, machine user vs. human user)
- Environment variables are not searchable in the docs, since we only point at the config files and explain how the variable names can be deduced from yaml files
- [Production Checklist](https://zitadel.com/docs/self-hosting/manage/production) makes no recommendation for envs vs config files

Proposal (to be discussed)
- Consistently use config with envs in the basic deploy examples
- Provide most important variables (see below) in the Configuration Options as list (and link to the files for full reference)
- Environment variables and their behavior should be described in more detail (variable name | mandatory (yes/no) | comments | defaults to)
- Reference the basic env variables from the deploy examples, such that people understand more easily how to change default values, as immediate next step (eg, password for admin)
- Make clear why our recommendation is config files in most cases (input from @fforootd about leaking values etc.)

Variables (incomplete, to be discussed)

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L21

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L24

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L29

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L56

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L57

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L58

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/defaults.yaml#L65

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/setup/steps.yaml#L24

https://github.com/zitadel/zitadel/blob/dc2a4ea92c6fefdea1648adb0983df11be90c5d8/cmd/setup/steps.yaml#L11

**Acceptance criteria**
- [ ] ...
- [ ] ...

### PR DESCRIPTION
**Pull request by mffap**
Adds a script to generate two markdown tables from steps.yaml and defaults.yaml. The table contains the variable name, description, and default values.
At the moment the files are generated in an output directory and have to be copied manually to the docs. This can be automated once we are confident that the solution works.

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [ ] My code has no repetitions
- [x] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by mffap** [comment]
@eliobischof @adlerhurst this should automatically generate the docs from the two files. Some default values do not make sense to present in the table. One obvious improvement would maybe to cut-off long strings and reference the files instead? One example are I think the email templates. Where we have an array of values as default values, I've already abbreviated as 'array[...]'.

Can you have a look, if that is ok, or any suggestions /feedback?

**Comment by mffap** [comment]
It should be considered that arrays / maps can't be passed at the moment due to the following bug: 
https://github.com/zitadel/zitadel/issues/6101

**Comment by eliobischof** [comment]
@mffap what do you think about this suggestion #6143?
It uses no generation code, but we still maintain configuration, their defaults and description at one place

**Comment by mffap** [comment]
> @mffap what do you think about this suggestion #6143? It uses no generation code, but we still maintain configuration, their defaults and description at one place

Certainly easier to maintain. However doesn't solve three separate issues, since the main issue is not the variable names but also the context and explanation to them (see issue https://github.com/zitadel/zitadel/issues/4976):
- More clear description of the parameters and their intend (can be also solved in the yaml)
- Types / expected values (can also be added to the yaml)
- User search: as mentioned in the issue https://github.com/zitadel/zitadel/issues/4976 - we also see quite some questions popping up in the chat and I can see them also in the docs search. Not sure what the solution is except to describe the main variables properly

**Comment by mffap** [comment]
@eliobischof we should maybe also check if we need to give a decisive recommendation in the production setup guide on which to use: config vs. env
Since maps/arrays are not possible, this must be imo config. I remember from a conversation with @fforootd that there are also considerations wrt opsec.

**Comment by eliobischof** [comment]
> > @mffap what do you think about this suggestion #6143? It uses no generation code, but we still maintain configuration, their defaults and description at one place
> 
> Certainly easier to maintain. However doesn't solve three separate issues, since the main issue is not the variable names but also the context and explanation to them (see issue #4976):
> 
> * More clear description of the parameters and their intend (can be also solved in the yaml)
> * Types / expected values (can also be added to the yaml)
> * User search: as mentioned in the issue [Docs: Configuration options vs environment variables #4976](https://github.com/zitadel/zitadel/issues/4976) - we also see quite some questions popping up in the chat and I can see them also in the docs search. Not sure what the solution is except to describe the main variables properly

Not sure if I fully understand your point. How does that not solve these three issues?
As you point out, the descriptions can be improved in the YAML and the types can be added, right?
Also, I think that Algolia should be able to crawl over all config descriptions and variables. 
image

Probably, [we can verify that in a week](https://docusaurus.io/docs/search#using-algolia-docsearch).

**Comment by eliobischof** [comment]
> @eliobischof we should maybe also check if we need to give a decisive recommendation in the production setup guide on which to use: config vs. env Since maps/arrays are not possible, this must be imo config. I remember from a conversation with @fforootd that there are also considerations wrt opsec.

I agree, will write a section.

**Comment by eliobischof** [comment]
> > @eliobischof we should maybe also check if we need to give a decisive recommendation in the production setup guide on which to use: config vs. env Since maps/arrays are not possible, this must be imo config. I remember from a conversation with @fforootd that there are also considerations wrt opsec.
> 
> I agree, will write a section.

Do you think this is good enough? https://github.com/zitadel/zitadel/pull/6143/commits/469a7f312175c6a9b21153cf64dba01c2e4c3ef8

**Comment by mffap** [comment]
> > > @mffap what do you think about this suggestion #6143? It uses no generation code, but we still maintain configuration, their defaults and description at one place
> > 
> > 
> > Certainly easier to maintain. However doesn't solve three separate issues, since the main issue is not the variable names but also the context and explanation to them (see issue #4976):
> > 
> > * More clear description of the parameters and their intend (can be also solved in the yaml)
> > * Types / expected values (can also be added to the yaml)
> > * User search: as mentioned in the issue [Docs: Configuration options vs environment variables #4976](https://github.com/zitadel/zitadel/issues/4976) - we also see quite some questions popping up in the chat and I can see them also in the docs search. Not sure what the solution is except to describe the main variables properly
> 
> Not sure if I fully understand your point. How does that not solve these three issues? As you point out, the descriptions can be improved in the YAML and the types can be added, right? Also, I think that Algolia should be able to crawl over all config descriptions and variables. image
> 
> Probably, [we can verify that in a week](https://docusaurus.io/docs/search#using-algolia-docsearch).

Ah ok, you've imported the files directly. Sorry didn't see that. Ok, we can try that, makes it for sure easier to handle.

**Comment by mffap** [comment]
Replaced by #6143

**Pull request closed without merging**
