### PR TITLE
feat(console): allow filter org by primary domain on instance

### LINKED ISSUE #7196: Allow filter org by primary domain on instance
If I want to search for an organization it's currently not possible to filter by primary domain in console.
Also console uses the wrong method to search for organizations on the instance overview. It currently uses `AuthService.ListMyProjectOrgs` instead of `AdminService.ListOrgs` which potentially hides orgs from an admin.

The following picture shows that there is no filter possibility for domains:
image

### PR DESCRIPTION
**Pull request by doncicuto**
In #7196 @adlerhurst proposed that it should be possible to filter organizations by the primary domain. Also he
pointed out that console uses the wrong method to search for organizations on the instance overview and that it currently uses AuthService.ListMyProjectOrgs instead of AdminService.ListOrgs which potentially hides orgs from an admin.

This PR adds primary domain to the organization filter and also implements the ListOrgs service adding it to admin.service.ts

The following video shows this PR in action:

https://github.com/zitadel/zitadel/assets/30386061/38b32586-6a64-4efe-9627-e726e49a7e73

Closes #7196 

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by hifabienne** [comment]
Hei @doncicuto 
Thanks. One thing that just came into my mind. I think we used the AuthService.ListMyProjectOrgs because it also needs to be able to query the list for people who are not an administrator. 
It probably also returns your own organization. I didn't check properly. But might make sense to have a look at it.
Maybe also as a note for the one who does the review :)

**Comment by doncicuto** [comment]
As always thanks @hifabienne. I'll try to test and see the differences between ListOrgs and ListMyProjectOrgs but I hope my reviewer helps me as usual to find the right call to the API. Cheers!

**Comment by peintnermax** [comment]
> As always thanks @hifabienne. I'll try to test and see the differences between ListOrgs and ListMyProjectOrgs but I hope my reviewer helps me as usual to find the right call to the API. Cheers!

This PR is good as it is.. The view was intended to show for admin users ('iam.read') therefore `listOrgs` is the correct call to make 👍

**Review by peintnermax — APPROVED** [review]
nice work @doncicuto Thank you a lot 💯

**Pull request merged**
