### PR TITLE
Optimize the maximum upload size for font.

### PR DESCRIPTION
**Pull request by Evsio0n**
Optimized the maximum upload size for font.
See issue #7054

Changed the maximum upload size from  `2MB` to `64MB`
Changed the maximum upload font size from `512MB` to `32MB`

This may cause a dependency if zitadel has a roadmap for using external links instead of uploading files.

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [x] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by livio-a** [comment]
@Evsio0n sorry for the late reply. We had some internal discussions about this, resp. the proposed sizes.

While we definitely see the problem, we don't want to generally allow that big files for performance reasons (e.g. storing the file in the database, serving the file for mobile devices / networks, ...)
We'd propose changing the allowed file sizes to a runtime configuration (defaults.yaml) so it can be configured based on needs and available possibilities (hardware/usage).

What do you think about that?

**Comment by Evsio0n** [comment]
My suggestion would be to place the above-mentioned content on external links (such as CDN hosting, or within the website directory). This can at least reduce the read/write operations on the database (As I’ve found, each time the login screen is loaded, it is actually a loading operation (i.e., reading the binary file from the database).) This indeed can affect performance. Therefore, I lean more toward using external URLs. I’m curious whether there has been any internal discussion or thoughts about Zitadel utilizing external resources?

**Comment by livio-a** [comment]
Hey @Evsio0n sorry for the late reply.

Yes we talked about serving those assets (incl. user avatars) from CDN / external sources as well.
We then need to look into how to handle that correctly in the content security policy for the login UI and console. Have not done so yet, but we're up for a proposal.

**Comment by Evsio0n** [comment]
Hi, Any proposal for the content resouces?

**Comment by livio-a** [comment]
I will close this PR since the increment of the upload size is not handleable at the moment.

**Pull request closed without merging**
