### PR TITLE
chore: added multiple browser support

### PR DESCRIPTION
**Pull request by thesephirot**
added firefox and chrome for finished releases, PR stay electron for speed

### CODE REVIEW

**Comment by eliobischof** [comment]
why don't we use a job matrix for parallel tests?
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Review by eliobischof — CHANGES_REQUESTED** [review]
https://github.com/zitadel/zitadel/pull/4161#issuecomment-1210620027

**Comment by thesephirot** [comment]
> why don't we use a job matrix for parallel tests and less config?
like this, only the tests rerun in a different configuration. in a matrix the complete docker compose stack needs to be doubled for reliable artifacts as they share the runners folder.

I guess this is a matter of speed, which runs faster. what do you think ?

**Comment by eliobischof** [comment]
I'd say the (unskipped) tests eventually have longer than zitadel and cockroach to become ready (i guess about 2m)

**Comment by thesephirot** [comment]
> I'd say the (unskipped) tests eventually have longer than zitadel and cockroach to become ready (i guess about 2m)

with more and more tests this might be significant. I amended it

**Review by eliobischof — APPROVED** [review]

**Review by eliobischof — COMMENTED** [review]
does this --browser flag really work?

**Comment by eliobischof** [comment]
> does this --browser flag really work?

I see, it does :-D 
Interesting

**Comment by thesephirot** [comment]
> > does this --browser flag really work?
> 
> I see, it does :-D Interesting

with the power of docker it gets interpreted as argument ;) yes it does

**Pull request merged**
