### PR TITLE
feat: get multiple users by id

### PR DESCRIPTION
**Pull request by ahmednfwela**
This is the first in a series of PRs that target https://github.com/zitadel/zitadel/issues/6186

here we introduce a new `InUserIDQuery` as a new possibility of `SearchQuery` to allow querying of multiple users by ids, this translates to a `WHERE Id IN (a,b,c)` query

Note: No tests were implemented since I have no idea where they should be written (it's my first time using go)

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by ahmednfwela** [comment]
cc @fforootd for review

**Comment by hifabienne** [comment]
Hei @ahmednfwela 
Thanks for your contribution. We will have a look at it.

**Comment by eliobischof** [comment]
Thank you @ahmednfwela :tada:

Can you add the following tests to `internal/query/search_query_test.go`, please?

```go
func TestNewInTextQuery(t *testing.T) {
	type args struct {
		column Column
		value  []string
	}
	tests := []struct {
		name    string
		args    args
		want    *InTextQuery
		wantErr func(error) bool
	}{
		{
			name: "empty values",
			args: args{
				column: testCol,
				value:  []string{},
			},
			wantErr: func(err error) bool {
				return errors.Is(err, ErrEmptyValues)
			},
		},
		{
			name: "no column",
			args: args{
				column: Column{},
				value:  []string{"adler", "hurst"},
			},
			wantErr: func(err error) bool {
				return errors.Is(err, ErrMissingColumn)
			},
		},
		{
			name: "no column name",
			args: args{
				column: testNoCol,
				value:  []string{"adler", "hurst"},
			},
			wantErr: func(err error) bool {
				return errors.Is(err, ErrMissingColumn)
			},
		},
		{
			name: "correct",
			args: args{
				column: testCol,
				value:  []string{"adler", "hurst"},
			},
			want: &InTextQuery{
				Column: testCol,
				Values: append([]string{"adler", "hurst"}),
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := NewInTextQuery(tt.args.column, tt.args.value)
			if err != nil && tt.wantErr == nil {
				t.Errorf("NewTextQuery() no error expected got %v", err)
				return
			} else if tt.wantErr != nil && !tt.wantErr(err) {
				t.Errorf("NewTextQuery() unexpeted error = %v", err)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("NewTextQuery() = %v, want %v", got, tt.want)
			}
		})
	}
}
 
func TestInTextQuery_comp(t *testing.T) {
	type fields struct {
		Column Column
		Values []string
	}
	type want struct {
		query interface{}
		isNil bool
	}
	tests := []struct {
		name   string
		fields fields
		want   want
	}{
		{
			name: "equals",
			fields: fields{
				Column: testCol,
				Values: []string{"Adler", "Hurst"},
			},
			want: want{
				query: sq.Eq{"test_table.test_col": []string{"Adler", "Hurst"}},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := &InTextQuery{
				Column: tt.fields.Column,
				Values: tt.fields.Values,
			}
			query := s.comp()
			if query == nil && tt.want.isNil {
				return
			} else if tt.want.isNil && query != nil {
				t.Error("query should not be nil")
			}
 
			if !reflect.DeepEqual(query, tt.want.query) {
				t.Errorf("wrong query: want: %v, (%T), got: %v, (%T)", tt.want.query, tt.want.query, query, query)
			}
		})
	}
}
```

Unfortunately, I'm not allowed to push directly to your fork.

**Comment by ahmednfwela** [comment]
@eliobischof Thanks, I have added the tests.

I am not sure why you can't push directly onto my fork tho, I thought by default contributors can push to any fork

**Comment by eliobischof** [comment]
> @eliobischof Thanks, I have added the tests.
> 
> I am not sure why you can't push directly onto my fork tho, I thought by default contributors can push to any fork

idk :man_shrugging:, but looks good to me now :slightly_smiling_face: 

Thanks again for your contribution :pray: 

We'd like to send you a small gift in return. If you like that too, please send us a mail to hi@zitadel.com. You will get a link to a form for the details.

**Comment by ahmednfwela** [comment]
Thanks @eliobischof , but having such a great open source project is enough gift for me 😄 
CI failure seems to be unrelated

**Comment by ahmednfwela** [comment]
@eliobischof Hi, is there a problem with the PR that I can fix ?

**Comment by ahmednfwela** [comment]
@eliobischof I have pushed a fix to the gocritic lints

**Review by fforootd — APPROVED** [review]

**Pull request merged**
