### PR TITLE
docs(cmd): document that human and service user can be used in the default instance

### PR DESCRIPTION
**Pull request by fforootd**
# Which Problems Are Solved

This solves a documentation issue raised here https://github.com/zitadel/zitadel/discussions/8217#discussioncomment-9936216

The behavior was changed with https://github.com/zitadel/zitadel/issues/6430

### CODE REVIEW

**Review by eliobischof — APPROVED** [review]

**Review by eliobischof — CHANGES_REQUESTED** [review]
do we have to change something in the steps.yaml, too?

**Comment by stebenz** [comment]
@eliobischof Yes that works the same, the only difference is that you also can create both at the same time now.

**Comment by eliobischof** [comment]
> @eliobischof Yes that works the same, the only difference is that you also can create both at the same time now.

How can default instance service users authenticate?

**Review by eliobischof — APPROVED** [review]
I added the same changes to the steps.yaml

**Pull request merged**
