### PR TITLE
feat: add otp name and make it configurable

### LINKED ISSUE #4712: Use system config for OTP name
As an end user of ZITADEL I want to be able to see for which system I have configured OTP and not that is is ZITADEL, because most of the time I do not know what ZITADEL is.

**Acceptance criteria**
- [ ] When I configure a new OTP I do not see ZITADEL somwhere
- [ ] When I add a new OTP I see the requested instance domain as "name" (take it from the instance context)

**Additional Context**
At the moment this is set in the default settings of ZITADEL and we always take it from there

### PR DESCRIPTION
**Pull request by bitfactory-sem-denbroeder**
```[tasklist]

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```
closes #4712

### CODE REVIEW

**Comment by eliobischof** [comment]
Answered here https://discord.com/channels/927474939156643850/927866013545025566/1093643788485927065

**Comment by hifabienne** [comment]
hei @bitfactory-sem-denbroeder thanks for your contribution.
are you done with that? can you please have a look at the conflicts?

**Comment by bitfactory-sem-denbroeder** [comment]
If the scope is just changing the name to the externalUrl the instance is running on, this PR should be fine, seems to be quite a small commit. Might be missing something, tested it locally and seemed to work. Resolved the merge conflict as well.

**Comment by eliobischof** [comment]
@livio-a I added commit https://github.com/zitadel/zitadel/pull/5631/commits/2581c81ca22a078c8c43eb799221b90651692d8d
I also tested locally that keys still work after issuer configuration change.
Can you verify my changes, plz?

**Review by livio-a — APPROVED** [review]

**Pull request merged**
