### PR TITLE
chore: changed trigger to follow release

### PR DESCRIPTION
**Pull request by thesephirot**

### CODE REVIEW

**Comment by fforootd** [comment]
Imo this is a chore:

**Comment by eliobischof** [comment]
> Imo this is a chore:

I think ci is better

**Review by eliobischof — DISMISSED** [review]
I'm sure, the event name should be workflow_run here: https://github.com/zitadel/zitadel/blob/997bd8f66feac8c66f5909d3a2cb1fb807e2814f/.github/workflows/e2e.yml#L30

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

But we can try

**Comment by thesephirot** [comment]
> I'm sure, the event name should be workflow_run here:
> 
> https://github.com/zitadel/zitadel/blob/997bd8f66feac8c66f5909d3a2cb1fb807e2814f/.github/workflows/e2e.yml#L30
> 
> https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run
> 
> But we can try

you are right, I`ll amend that

**Review by eliobischof — APPROVED** [review]

**Pull request merged**
