### PR TITLE
feat(cnsl): docs link can be customized and custom button is available

### LINKED ISSUE #7175: Customize the profile 'Documentation' button
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

On the user Home/Profile page there is a 'Documentation' button that hyperlinks to https://zitadel.com/docs . I would like to have this button be customizable (i.e., change the name of the button & the hyperlink

The code for the hyperlink appears to be located here? 
console/src/app/pages/home/home.component.html

The reason being: most basic users have no interest/need to refer to the Zitadel documentation from their profile page. They're already aware in my case it is zitadel since our url is zitadel.example.com. Something that would be **incredibly** useful is if this hyperlink could be changed to point towards **internal documentation**. That way we can use the profile page to help users navigate the sites we are using Zitadel to protect

`    <div class="home-grid-container">
      <a href="https://zitadel.com/docs" target="_blank" rel="noreferrer" class="grid-item">
        <div
          class="icon-wrapper"
          [ngStyle]="{
            background: (themeService.isDarkTheme | async) ? bluedark + 50 : bluelight + 50
          }"
        >`

### Describe your ideal solution

A UI interface would be ideal, specifically located within the Instance Settings section & the Organization Settings section. Since different organizations may have their own documentation sites. 

### Version

_No response_

### Environment

Self-hosted

### Additional Context

hosted within docker

### PR DESCRIPTION
**Pull request by doncicuto**
Although Zitadel highly recommends to build your own UI for your user self service, this PR adds two features requested by some users in issue #7175 

The Privacy Policy setting link has been renamed to External Links

image

External links now allow to change the Documentation button link in case you want that button in the console to point to your company/organization own documentation. If the link is empty, the documentation button won't be shown. By default the documentation button points to Zitadel docs.

image

Also the console has now an option to have a custom button that can be named and have an associated link to special needs for the company/organization. If the custom button text is empty no button will be shown (this is the default).

image

image

You can configure default values when Zitadel is initialized either using defaults.yaml or environment variables

image

Thanks @K-J-VV and @rejochandran for your interest in this feature

Should close #7175

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [X] Critical parts are tested automatically
- [X] Where possible E2E tests are implemented
- [X] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by doncicuto** [comment]
Sure @peintnermax let me have a look

**Comment by doncicuto** [comment]
Hi @peintnermax I've uploaded your requested changes. Thanks for the suggestion it works better indeed!

**Comment by peintnermax** [comment]
> Hi @peintnermax I've uploaded your requested changes. Thanks for the suggestion it works better indeed!

Perfect.. Thx for your changes.. works nicely 😎

**Review by peintnermax — DISMISSED** [review]

**Comment by peintnermax** [comment]
@doncicuto I noticed the linter is failing. Could you fix the issues? appreciate it 😎👍

**Comment by doncicuto** [comment]
Sorry @peintnermax I missed that one, I've replaced one of those deprecated prepareCommands, hope it works fine now. 

My machine struggles with memory when performing full tests so sorry if some errors accidently slips to CI (wish I had another 16GB module :disappointed:)

**Review by peintnermax — APPROVED** [review]

**Pull request merged**
