### PR TITLE
feat(console): azure ad provider

### PR DESCRIPTION
**Pull request by peintnermax**
Partial of #4433 

```[tasklist]
### Definition of Ready
- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```

### CODE REVIEW

**Comment by peintnermax** [comment]
@eliobischof can you review after #5441 has been merged? thx

**Review by eliobischof — DISMISSED** [review]

**Review by eliobischof — COMMENTED** [review]
Didn't you want to make the templates more dry with the last template?

**Comment by peintnermax** [comment]
> Didn't you want to make the templates more dry with the last template?

I can do that here or in a seperate PR if its easier for you

**Comment by eliobischof** [comment]
> > Didn't you want to make the templates more dry with the last template?
> 
> I can do that here or in a seperate PR if its easier for you

Maybe a separate PR is better

**Pull request merged**
