### PR TITLE
feat: Add UUIDv7 as an ID generator and make choosing the generator configurable

### PR DESCRIPTION
**Pull request by borisroman**
This is a possible implementation for #8305, and fully open for discussion.

Since the generator is used as a singleton, I have applied this pattern consistently throughout the codebase.

A specific point of intrest is the  `TokenDelimiter` in `internal/command/oidc_session.go`. This used to be a `-`, however that is not a possibility when using UUID-based ids. So I've changed this to a `.` which is valid for it's use cases incl. URL-usage without the need for encoding. As far as I could check, it's not stored in the DB, so no migration is necessary.

The ID is also used as a serial for the SAML certificates. A numeric helper function has been added to facilitate this.

The regex for the IDP API path has been adjusted in `internal/api/idp/idp.go` to support UUID-based ids.

I've ran all unit and integration tests for both CockroachDB and Postgres, for both `IDGenerator: 0` and `IDGenerator: 1`.

Happy to hear your thoughts.

### CODE REVIEW

**Comment by livio-a** [comment]
A change on the `TokenDelimiter` would invalidate all active tokens, which we want to avoid when possible.
But let me have a closer look at the PR and discuss this also internally in the next few days.

**Comment by livio-a** [comment]
Hey @borisroman 

We were finally able to discuss this topic. Sorry for the late reply.

There are multiple problems with the `TokenDelimiter` and corresponding mechanisms (see also https://github.com/zitadel/zitadel/issues/8237). Since IDs can (at some parts) already be provided through the API any delimiter can cause an issue.
As discussed with @muhlemmer, we want / need to migrate to a JSON object, resp. its serialized string format (i.e. base64) where needed e.g. `jti` claim in token.

We propose to put this PR on hold and first migrate it to JSON to be able to handle properly.

**Comment by livio-a** [comment]
@borisroman we currently do not have the time to switch to the JSON format.
Do you want to have a look at that or do you use you forked version anyway and we can close this PR for now?

**Comment by hifabienne** [comment]
Hei @borisroman 
Do you still work on this issue?

**Comment by muhlemmer** [comment]
As this currently will not work and #8693 didn't progress, I will close this PR. It can be reopened when all concerns are resolved.

**Pull request closed without merging**
