### PR TITLE
fix(console): set options, idp layout

### PR DESCRIPTION
**Pull request by peintnermax**
Partial of #5654 

```[tasklist]

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```

### CODE REVIEW

**Review by hifabienne — DISMISSED** [review]

**Review by adlerhurst — CHANGES_REQUESTED** [review]
line hight isn't the same for each input field and header: 
image

**Comment by adlerhurst** [comment]
and if it's not too much work please align the naming of the azure tenant types with their wording. customer should be consumer

**Review by adlerhurst — CHANGES_REQUESTED** [review]
undefined is not translated in azure: 
image

**Comment by adlerhurst** [comment]
@peintnermax and the tenant id field is always shown. It should only be shown as soon as the undefined type is selected

**Review by adlerhurst — APPROVED** [review]

**Review by adlerhurst — APPROVED** [review]

**Pull request merged**
