### PR TITLE
chore: sunset v1 docs

### PR DESCRIPTION
**Pull request by fforootd**
- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by mffap** [comment]
@fforootd we need also to remove all references in the legal section. Should I quickly have a look and push on this one?

**Comment by fforootd** [comment]
> @fforootd we need also to remove all references in the legal section. Should I quickly have a look and push on this one?

Ah yes, that would be a blast. 

I think we mention it at two places support-services and service-level

**Comment by livio-a** [comment]
> @fforootd we need also to remove all references in the legal section. Should I quickly have a look and push on this one?

Yes found two mentions

**Comment by mffap** [comment]
Ok, will do.

**Review by livio-a — APPROVED** [review]

**Pull request merged**
