### PR TITLE
docs(adopter): devOS: Sanity Edition org

### PR DESCRIPTION
**Pull request by asoji**
N/A

### CODE REVIEW

**Comment by hifabienne** [comment]
Hi @asoji 
Thanks a lot for adding to the adopters list.
If you like to get a small present from us, please reach out to hi@zitadel.com

**Comment by hifabienne** [comment]
Hi @asoji 
The branch is currently out of date, which means you will have to merge main back.
You can also enable on your pr that we are allowed to remerge main, this makes it easier to get them into, as we currently have some open prs on the adopters file.

**Comment by asoji** [comment]
> Hi @asoji The branch is currently out of date, which means you will have to merge main back. You can also enable on your pr that we are allowed to remerge main, this makes it easier to get them into, as we currently have some open prs on the adopters file.

oh.. oops.. i'll try to figure this out, my bad 😅

**Comment by asoji** [comment]
I assume this is what I need to do?

image

**Comment by hifabienne** [comment]
Hei @asoji 
This is the wrong setting, it should be on your pr.
It should be "allow edits from maintainers"

**Comment by asoji** [comment]
Good morning,

hm, I looked at GitHub's documentation and compared with this PR, i don't see such an option?

image

**Pull request merged**
