### PR TITLE
feat(console): add e2e tests for metadata

### PR DESCRIPTION
**Pull request by peintnermax**
- [x] add user metadata
- [ ] remove user metadata
- [x] add org metadata
- [ ] remove org metadata

### CODE REVIEW

**Comment by livio-a** [comment]
@peintnermax i believe we should plan this in for a next / future sprint?

**Comment by peintnermax** [comment]
> @peintnermax i believe we should plan this in for a next / future sprint?

fine by me.. @eliobischof had some improvements for the e2e in general so we should consider merging them even before 👍

**Comment by hifabienne** [comment]
@peintnermax Can we close this one?

**Comment by peintnermax** [comment]
yes.. we should redesign the metadata component for better UX and then look at it 👍

**Pull request closed without merging**
