### PR TITLE
ci(e2e): skip flaky project tests

### PR DESCRIPTION
**Pull request by thesephirot**
skipped flaky project tests and test the PR function with it

### CODE REVIEW

**Review by eliobischof — COMMENTED** [review]
Are all project tests flaky? Not just the delete tests?

**Comment by thesephirot** [comment]
> Are all project tests flaky? Not just the delete tests?

just delete, but we need to fix the projects as a whole if we want to be able to test instances in the future. otherwise the projects will be created and not deleted.

**Comment by eliobischof** [comment]
> > Are all project tests flaky? Not just the delete tests?
> 
> just delete, but we need to fix the projects as a whole if we want to be able to test instances in the future. otherwise the projects will be created and not deleted.

No, tests don't depend on each other. In the before hooks that is ensured for each test via api calls.
image

**Comment by thesephirot** [comment]
> > > Are all project tests flaky? Not just the delete tests?
> > 
> > 
> > just delete, but we need to fix the projects as a whole if we want to be able to test instances in the future. otherwise the projects will be created and not deleted.
> 
> No, tests don't depend on each other. In the before hooks that is ensured for each test via api calls. image

I overlooked that, that makes sense. Will change to "project delete" instead

**Comment by thesephirot** [comment]
> > > > Are all project tests flaky? Not just the delete tests?
> > > 
> > > 
> > > just delete, but we need to fix the projects as a whole if we want to be able to test instances in the future. otherwise the projects will be created and not deleted.
> > 
> > 
> > No, tests don't depend on each other. In the before hooks that is ensured for each test via api calls. image
> 
> I overlooked that, that makes sense. Will change to "project delete" instead

done

**Review by eliobischof — APPROVED** [review]

**Pull request merged**
