### PR TITLE
[DO NOT MERGE] feat(console): big UI/UX improvements

### PR DESCRIPTION
**Pull request by peintnermax**
Things to do:

- [x] User memberships
- [x] fix user filter
- [x] actions
- [x] mobile nav + mobile user subnav 
- [x] cleanup detail pages
- [x] hide nav bar on policy pages
- [x] show change target of policies

Bildschirmfoto 2021-12-16 um 17 02 25

### CODE REVIEW

**Comment by peintnermax** [comment]
@fforootd the branch will soon be ready to review, so it would be nice to have a netlify deployment.. Could you take a look at that? :D

**Comment by fforootd** [comment]
> @fforootd the branch will soon be ready to review, so it would be nice to have a netlify deployment.. Could you take a look at that? :D 

Yes I will check later today how we can deploy the assets somewhere

**Comment by fforootd** [comment]
i guess this will be replaced with #3525 and others

**Comment by peintnermax** [comment]
exactly

**Pull request closed without merging**
