### PR TITLE
docs: add nodejs-nestjs to introduction.mdx

### PR DESCRIPTION
**Pull request by tafaust**
Add Node.js NestJS framework to the list.

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by tafaust** [comment]
Should not be merged before https://github.com/zitadel/zitadel/pull/7136

**Review by peintnermax — CHANGES_REQUESTED** [review]
Hi @tafaust ,
could you add the guide to the sidebars.js so that it will be displayed in the navigation?
https://github.com/zitadel/zitadel/blob/main/docs/sidebars.js#L28C42-L28C42
thx a lot 👍

**Comment by tafaust** [comment]
> Hi @tafaust , could you add the guide to the sidebars.js so that it will be displayed in the navigation? https://github.com/zitadel/zitadel/blob/main/docs/sidebars.js#L28C42-L28C42 thx a lot 👍

Hi @peintnermax,
I thought that was the introduction.mdx? Can you help me to do the changes? :)
Best, Thomas

**Comment by peintnermax** [comment]
> > Hi @tafaust , could you add the guide to the sidebars.js so that it will be displayed in the navigation? https://github.com/zitadel/zitadel/blob/main/docs/sidebars.js#L28C42-L28C42 thx a lot 👍
> 
> Hi @peintnermax, I thought that was the introduction.mdx? Can you help me to do the changes? :)

sure I've added the missing line 👍

**Review by peintnermax — APPROVED** [review]

**Pull request merged**
