### PR TITLE
fix(account-selection): use font color as color for labels

### PR DESCRIPTION
**Pull request by dsiscout**
### Definition of Ready

- [ X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [x] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [X] All open todos and follow ups are defined in a new ticket and justified
- [X] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [X] Critical parts are tested automatically
- [X] Where possible E2E tests are implemented
- [X] Documentation/examples are up-to-date
- [X] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

The colors configured in the instance resp. project settings for the font were not used for labels. See #5505 for more infos.

### CODE REVIEW

**Comment by hifabienne** [comment]
Hei @dsiscout 
I quickly had a look, and from my perspective it doesn't look like the issue #5505 gets fixed by this.
Can you please add a short description in your PR what the issue is about to solve?

**Comment by dsiscout** [comment]
Hello @hifabienne 

The issue is, that for labels, the font color in the settings is not taken (https://github.com/zitadel/zitadel/issues/5505). In our case, we do not want to differentiate between light and dark mode, so we use the same configs on both. But the label color is not configurable, which is why on our account selection the username is white:
Screenshot from 2023-09-09 20-13-24

In this PR, what I am basically doing is, setting the label color same as the font color, and now when I test locally it looks like this:
Screenshot from 2023-09-09 20-15-31

Let me know if you need further information or anything I should adjust in the PR.

Best regards

**Comment by livio-a** [comment]
I think the initial idea was to distinguish the color of labels and texts.

This change would get rid of this, which i'm fine as it solves at least some part of the light / dark problems mentioned in the issue.
It will obviously have an impact on developers, resp. their design as soon as the change something and would also get another color for their labels.

IMO we should move forward as this solves more problems than it could potentially cause.
@hifabienne any objections?

**Comment by hifabienne** [comment]
@livio-a Yes I am with you.

**Review by livio-a — APPROVED** [review]

**Comment by livio-a** [comment]
@dsiscout thanks for this contribution 😃 

If you'd like to have a small gift in return, please send us a mail to [hi@zitadel.com](mailto:hi@zitadel.com). We will send you a form with questions about your address and shirt size.

**Pull request merged**
