### PR TITLE
docs: create secrets concepts and update docusaurus to stable release

### PR DESCRIPTION
**Pull request by fforootd**

### CODE REVIEW

**Comment by fforootd** [comment]
@livio-a since you wrote a lot of that code I think you should review this 😁

**Comment by mffap** [comment]
@fforootd can we at least once mention "credentials" for search, please?

**Comment by fforootd** [comment]
> can we at least once mention "credentials" for search, please?

Sure can do 😁 I will include this word to clarify the usasge

**Comment by fforootd** [comment]
@mffap I added credentials

**Comment by mffap** [comment]
> @livio-a since you wrote a lot of that code I think you should review this 😁

Very nice. Thanks :) The overview is clean.
I'll let @livio-a give the approval re contents.

**Review by livio-a — APPROVED** [review]

**Pull request merged**
