### PR TITLE
fix: fix slice init length

### PR DESCRIPTION
**Pull request by chuangjinglu**
# Which Problems Are Solved

The intention here should be to initialize a slice with a capacity of len(queriedOrgs.Orgs) rather than initializing the length of this slice.

the online demo: https://go.dev/play/p/vNUPNjdb2gJ

# How the Problems Are Solved

use `processedOrgs := make([]string, 0, len(queriedOrgs.Orgs))`

# Additional Changes

None

# Additional Context

None

### CODE REVIEW

**Comment by muhlemmer** [comment]
@chuangjinglu thanks for the fix. Can you please edit the PR description and replace the texts as described?

> Replace this example text with a concise list of changes that this PR introduces.
For example:...

**Comment by chuangjinglu** [comment]
> @chuangjinglu thanks for the fix. Can you please edit the PR description and replace the texts as described?
> 
> > Replace this example text with a concise list of changes that this PR introduces.
> > For example:...

Of course. Modified.

Please review again.

**Comment by muhlemmer** [comment]
I still see the example texts in the PR body. Did you forget to safe the changes?

**Comment by hifabienne** [comment]
hei @chuangjinglu do you still work on this? did you see the last comment from @muhlemmer

**Comment by chuangjinglu** [comment]
> I still see the example texts in the PR body. Did you forget to safe the changes?

Sorry for the late processing, it has been modified

**Review by muhlemmer — APPROVED** [review]

**Comment by muhlemmer** [comment]
hey @chuangjinglu thanks for the contribution.

If you'd like to have a small gift in return, please send us a mail to hi@zitadel.com. We will send you a form with questions about your address and shirt size.

**Comment by chuangjinglu** [comment]
> hey @chuangjinglu thanks for the contribution.
> 
> If you'd like to have a small gift in return, please send us a mail to [hi@zitadel.com](mailto:hi@zitadel.com). We will send you a form with questions about your address and shirt size.

Thank you! Very happy and honored.

**Pull request merged**
