### PR TITLE
docs: corrected number to string

### PR DESCRIPTION
**Pull request by thesephirot**

### CODE REVIEW

**Review by eliobischof — APPROVED** [review]

**Comment by eliobischof** [comment]
changed the title to docs: ...

**Review by eliobischof — COMMENTED** [review]
Do we need deploy/...

**Review by eliobischof — CHANGES_REQUESTED** [review]
shouldn't that go to docs/docs/guides/deploy/

**Comment by thesephirot** [comment]
> 

we had this discussion already, I didn't changed the location, but a yaml that was broken

**Comment by thesephirot** [comment]
to me this is an installation yaml, not a documentation

**Comment by eliobischof** [comment]
Why is installation yaml and docs mutually exclusive? We have a section in the docs for exactly that.

**Review by eliobischof — APPROVED** [review]
The change doesn't hurt, I guess

**Comment by thesephirot** [comment]
close

**Pull request closed without merging**
