### PR TITLE
chore: Xforward cypress to show browser locally

### PR DESCRIPTION
**Pull request by thesephirot**

### CODE REVIEW

**Comment by mffap** [comment]
@thesephirot I've added the how for win10 with wsl2 directly to the contribution guide. Maybe we need to consolidate later.

**Comment by eliobischof** [comment]
Why do you want to run cypress open in a container?

**Comment by peintnermax** [comment]
I‘d preferably use the node modules from /e2e as it keeps dependencies there and it makes contributions easier.. but should then get rid of the container in the action..

**Comment by hifabienne** [comment]
We do not need this for the moment

**Pull request closed without merging**
