### PR TITLE
docs: improve template handling for search results

### PR DESCRIPTION
**Pull request by fforootd**

### CODE REVIEW

**Comment by fforootd** [comment]
This is a prerequisite to make #4037 and #caddy work

**Comment by eliobischof** [comment]
We should do the same for the */configure docs

**Review by eliobischof — CHANGES_REQUESTED** [review]
https://github.com/zitadel/zitadel/pull/4043#issuecomment-1194050711

**Comment by fforootd** [comment]
True was not aware that it utilizes the same.

**Comment by fforootd** [comment]
@eliobischof there you go

**Review by eliobischof — APPROVED** [review]

**Pull request merged**
