### PR TITLE
perf(oidc): remove get user by ID from jwt profile grant

### PR DESCRIPTION
**Pull request by muhlemmer**
# Which Problems Are Solved

Improve performance by removing a GetUserByID call. The call also executed a Trigger on projections, which significantly impacted concurrent requests.

# How the Problems Are Solved

Token creation needs information from the user, such as the resource owner and access token type.

For client credentials this is solved in a single search. By getting the user by username (`client_id`), the user details and secret were obtained in a single query. After that verification and token creation can proceed. For JWT profile it is a bit more complex. We didn't know anything about the user until after JWT verification.
The verification did a query for the AuthN key and after that we did a GetUserByID to get remaining details.

This change uses a joined query when the OIDC library calls the `GetKeyByIDAndClientID` method on the token storage. The found user details are set to the verifieer object and returned after verification is completed.
It is safe because the `jwtProfileKeyStorage` is a single-use object as a wrapper around `query.Queries`.
This way getting the public key and user details are obtained in a single query.

# Additional Changes

- Correctly set the `client_id` field with machine's username.

# Additional Context

- Related to: https://github.com/zitadel/zitadel/issues/8352

### CODE REVIEW

**Comment by muhlemmer** [comment]
Local load test on `main` branch

```
     checks...............................: 100.00% ✓ 131116     ✗ 0    
     data_received........................: 87 MB   435 kB/s
     data_sent............................: 56 MB   281 kB/s
     http_req_blocked.....................: min=942ns    avg=2.64µs  max=465.48µs p(50)=2.27µs  p(95)=4.18µs   p(99)=6.81µs  
     http_req_connecting..................: min=0s       avg=74ns    max=412.83µs p(50)=0s      p(95)=0s       p(99)=0s      
     http_req_duration....................: min=1.01ms   avg=44.84ms max=996.83ms p(50)=16.17ms p(95)=91.47ms  p(99)=100.04ms
       { expected_response:true }.........: min=1.01ms   avg=44.84ms max=996.83ms p(50)=16.17ms p(95)=91.47ms  p(99)=100.04ms
     http_req_failed......................: 0.00%   ✓ 0          ✗ 87452
     http_req_receiving...................: min=14.93µs  avg=42.45µs max=3.77ms   p(50)=38.41µs p(95)=68.41µs  p(99)=98.17µs 
     http_req_sending.....................: min=6.05µs   avg=15.2µs  max=695.93µs p(50)=13.9µs  p(95)=24.06µs  p(99)=36.39µs 
     http_req_tls_handshaking.............: min=0s       avg=0s      max=0s       p(50)=0s      p(95)=0s       p(99)=0s      
     http_req_waiting.....................: min=943.78µs avg=44.78ms max=996.75ms p(50)=16.11ms p(95)=91.41ms  p(99)=99.97ms 
     http_reqs............................: 87452   435.741697/s
     iteration_duration...................: min=38.92ms  avg=91.57ms max=1s       p(50)=89.23ms p(95)=100.91ms p(99)=112.15ms
     iterations...........................: 43681   217.64663/s
     login_ui_enter_login_name_duration...: min=29.97ms  avg=29.97ms max=29.97ms  p(50)=29.97ms p(95)=29.97ms  p(99)=29.97ms 
     login_ui_enter_password_duration.....: min=1.01ms   avg=1.01ms  max=1.01ms   p(50)=1.01ms  p(95)=1.01ms   p(99)=1.01ms  
     login_ui_init_login_duration.........: min=13.49ms  avg=13.49ms max=13.49ms  p(50)=13.49ms p(95)=13.49ms  p(99)=13.49ms 
     login_ui_token_duration..............: min=15.12ms  avg=15.12ms max=15.12ms  p(50)=15.12ms p(95)=15.12ms  p(99)=15.12ms 
     oidc_token_duration..................: min=22.87ms  avg=86.25ms max=996.83ms p(50)=84.08ms p(95)=95.11ms  p(99)=105.47ms
     oidc_user_info_duration..............: min=1.44ms   avg=3.46ms  max=16.03ms  p(50)=3.43ms  p(95)=5.04ms   p(99)=6.33ms  
     org_create_org_duration..............: min=16.69ms  avg=16.69ms max=16.69ms  p(50)=16.69ms p(95)=16.69ms  p(99)=16.69ms 
     user_add_machine_key_duration........: min=10.98ms  avg=36.67ms max=62.38ms  p(50)=36.69ms p(95)=59.51ms  p(99)=61.81ms 
     user_create_machine_duration.........: min=16.59ms  avg=56.21ms max=101.04ms p(50)=53.35ms p(95)=96.38ms  p(99)=100.11ms
     vus..................................: 20      min=20       max=20 
     vus_max..............................: 20      min=20       max=20 


running (3m20.7s), 00/20 VUs, 43681 complete and 0 interrupted iterations
default ✓ [======================================] 20 VUs  3m20s
```

**Comment by muhlemmer** [comment]
On this branch

```
     checks...............................: 100.00% ✓ 353761      ✗ 0     
     data_received........................: 233 MB  1.2 MB/s
     data_sent............................: 152 MB  756 kB/s
     http_req_blocked.....................: min=872ns    avg=3.29µs   max=4.06ms   p(50)=2.92µs   p(95)=4.43µs   p(99)=7.58µs  
     http_req_connecting..................: min=0s       avg=28ns     max=516.06µs p(50)=0s       p(95)=0s       p(99)=0s      
     http_req_duration....................: min=827.37µs avg=15.69ms  max=611.98ms p(50)=14.42ms  p(95)=26.59ms  p(99)=34.13ms 
       { expected_response:true }.........: min=827.37µs avg=15.69ms  max=611.98ms p(50)=14.42ms  p(95)=26.59ms  p(99)=34.13ms 
     http_req_failed......................: 0.00%   ✓ 0           ✗ 235882
     http_req_receiving...................: min=12.83µs  avg=50.92µs  max=6.31ms   p(50)=41.54µs  p(95)=73.14µs  p(99)=189.45µs
     http_req_sending.....................: min=5.66µs   avg=18.72µs  max=16.24ms  p(50)=15.8µs   p(95)=25.09µs  p(99)=40.81µs 
     http_req_tls_handshaking.............: min=0s       avg=0s       max=0s       p(50)=0s       p(95)=0s       p(99)=0s      
     http_req_waiting.....................: min=760.54µs avg=15.62ms  max=611.93ms p(50)=14.35ms  p(95)=26.51ms  p(99)=34.02ms 
     http_reqs............................: 235882  1175.417592/s
     iteration_duration...................: min=15.12ms  avg=33.91ms  max=620.77ms p(50)=32.79ms  p(95)=44.82ms  p(99)=112.93ms
     iterations...........................: 117896  587.484558/s
     login_ui_enter_login_name_duration...: min=41.4ms   avg=41.4ms   max=41.4ms   p(50)=41.4ms   p(95)=41.4ms   p(99)=41.4ms  
     login_ui_enter_password_duration.....: min=827.37µs avg=827.37µs max=827.37µs p(50)=827.37µs p(95)=827.37µs p(99)=827.37µs
     login_ui_init_login_duration.........: min=16.19ms  avg=16.19ms  max=16.19ms  p(50)=16.19ms  p(95)=16.19ms  p(99)=16.19ms 
     login_ui_token_duration..............: min=19.78ms  avg=19.78ms  max=19.78ms  p(50)=19.78ms  p(95)=19.78ms  p(99)=19.78ms 
     oidc_token_duration..................: min=8.39ms   avg=20.62ms  max=611.98ms p(50)=18.92ms  p(95)=28.85ms  p(99)=103.51ms
     oidc_user_info_duration..............: min=2.61ms   avg=10.74ms  max=75.58ms  p(50)=10.03ms  p(95)=18.45ms  p(99)=22.68ms 
     org_create_org_duration..............: min=17.26ms  avg=17.26ms  max=17.26ms  p(50)=17.26ms  p(95)=17.26ms  p(99)=17.26ms 
     user_add_machine_key_duration........: min=10.77ms  avg=37.77ms  max=64.98ms  p(50)=35.62ms  p(95)=62.95ms  p(99)=64.57ms 
     user_create_machine_duration.........: min=21.41ms  avg=59.12ms  max=98ms     p(50)=57.77ms  p(95)=95.48ms  p(99)=97.5ms  
     vus..................................: 20      min=20        max=20  
     vus_max..............................: 20      min=20        max=20  


running (3m20.7s), 00/20 VUs, 117896 complete and 0 interrupted iterations
default ✓ [======================================] 20 VUs  3m20s
```
That's a 2.6x improvement. Note that at this stage k6, zitadel and postgres are competing for resources on my system. A load test in a deployment might give better numbers.

**Review by adlerhurst — APPROVED** [review]

**Comment by adlerhurst** [comment]
just saw the benchmarks great job 🥳

**Comment by fforootd** [comment]
Oh wow, great job!

**Pull request merged**
