### PR TITLE
chore: improve wording

### PR DESCRIPTION
**Pull request by fforootd**

### CODE REVIEW

**Comment by mffap** [comment]
@fforootd this would be already an improvement. Should we go with it for the moment?

**Review by eliobischof — CHANGES_REQUESTED** [review]
found typos. i'm going to fix them...

**Review by eliobischof — APPROVED** [review]

**Comment by fforootd** [comment]
@mffap @eliobischof yeah we can go with this already if you like it 😁

**Comment by mffap** [comment]
> @mffap @eliobischof yeah we can go with this already if you like it 😁

Yes, let's go. We need to do a quick review anyways when we completed splitting the example repo and tuned the integration section in the docs. But that'll take a couple of days.

**Pull request merged**
