### PR TITLE
fix(user): enable use of usernames w/o email addresses if org settings permit

### PR DESCRIPTION
**Pull request by cyb3rd0g1**
Resolution for #4052. Also switched email check logic to look at the value after the last "@" since this is technically possible per the RFC.

https://stackoverflow.com/questions/12355858/how-many-symbol-can-be-in-an-email-address/12355882#12355882

I also noticed that a similar thing was happening in the `createHuman` function and updated that to conform to the same logic.

### CODE REVIEW

**Comment by cyb3rd0g1** [comment]
Looks like tests need to be updated, will go ahead and do that if we are happy with the overall approachc

**Comment by fforootd** [comment]
@hifabienne @livio-a @adlerhurst who is going to have a look into this?

**Review by livio-a — COMMENTED** [review]
@cyb3rd0g1 thanks again for the PR

LGTM... you can go ahead an update the tests

can you please check the indent
image

**Comment by livio-a** [comment]
closed in favour of #4852
thank you @cyb3rd0g1 for the groundwork

**Pull request closed without merging**
