### PR TITLE
fix(console): refine onboarding styles and behavior, i18n

### PR DESCRIPTION
**Pull request by peintnermax**
Partial of #5566

```[tasklist]

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```

### CODE REVIEW

**Review by eliobischof — CHANGES_REQUESTED** [review]
Let's e2e test the onboarding view.
Please also check the DoR boxes.

**Comment by peintnermax** [comment]
> Let's e2e test the onboarding view. Please also check the DoR boxes.

what exactly do you want to test?

**Review by eliobischof — CHANGES_REQUESTED** [review]
what do you think about this? #5617

**Comment by eliobischof** [comment]
I aggree, writing good e2e tests for the onboarding is a lot easier when https://github.com/zitadel/zitadel/pull/5618 is merged.

**Comment by juergrinaldi** [comment]
@peintnermax @eliobischof Do you have a ETA when the PR is through for me to review? (as there's a blogpost for @dakshitha dependent on this). Thanks. 😃

**Comment by eliobischof** [comment]
> what do you think about this? #5617

The rest looks good to me

**Comment by eliobischof** [comment]
> @peintnermax @eliobischof Do you have a ETA when the PR is through for me to review? (as there's a blogpost for @dakshitha dependent on this). Thanks. smiley

Do you need it ASAP? Then I can deploy it to our dev environment.

**Comment by juergrinaldi** [comment]
> > @peintnermax @eliobischof Do you have a ETA when the PR is through for me to review? (as there's a blogpost for @dakshitha dependent on this). Thanks. smiley
> 
> Do you need it ASAP? Then I can deploy it to our dev environment.

Yes please. 👍  As @dakshitha wants to publish the blogpost today and I need to change the screenshots.

**Comment by peintnermax** [comment]
> what do you think about this? #5617

I think we have to discuss this a little further as some events wont show up again.. I would address this seperately as it has nothing to do with the onboarding or does it? the events are filtered anyways 🤔

**Review by eliobischof — APPROVED** [review]

**Pull request merged**
