### PR TITLE
fix: negative and non-integer values in UI for token lifetimes

### PR DESCRIPTION
**Pull request by CalRobert**
# Which Problems Are Solved

User can enter negative and non-integer values for access, id, and refresh token lifetimes.

# How the Problems Are Solved

Frontend validation of inputs stops user from entering incorrect values

# Additional Changes

None

# Additional Context
Screenshot from 2024-08-09 06-49-36

### CODE REVIEW

**Comment by hifabienne** [comment]
hei @CalRobert 
Please update the pr description and put it to ready for review as soon as you are done, so we know we can have a look at it

**Comment by CalRobert** [comment]
> hei @CalRobert Please update the pr description and put it to ready for review as soon as you are done, so we know we can have a look at it

Thanks - will do, marked it as draft so nobody would waste time reviewing a PR that isn't ready yet of course

**Comment by hifabienne** [comment]
hei @CalRobert 
Do you still intend to work on this?

**Comment by CalRobert** [comment]
> hei @CalRobert Do you still intend to work on this?

Realistically speaking probably not, sorry

**Pull request closed without merging**
