### PR TITLE
fix: go back to user selection from other user

### LINKED ISSUE #2097: No back to user selection after hitting 'other user'
As a end user I want to be able to navigate back to the select account list after I have clicked "other user" or selected a specific user.

**Acceptance Criteria**
- [ ] I can navigate back to the select account screen by clicking a back button, after I have choosen "other account"

**Additional Context**
After clicking on 'Other User' on the login prompt (instead of selecting an existing user) I have no UI link back to the user selection (browser 'back button' works, but it's not very intuitive for most users).

image

image

### PR DESCRIPTION
**Pull request by doncicuto**
As @juergrinaldi stated:

> As a end user I want to be able to navigate back to the select account list after I have clicked "other user" or selected a specific user.

Acceptance Criteria

- [X] I can navigate back to the select account screen by clicking a back button, after I have choosen "other account"

The code in this PR adds a back button that shows only if we've clicked on the "other user" button (checks if we're in /userselection). If we click the back button the browser's history back is used simulating that we've clicked on the browser's back button.

This a video showing the proposed solution: https://youtu.be/en6s57AOZm8

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [X] PR is linked to the corresponding user story
- [X] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [X] Functionality of the acceptance criteria is checked manually on the dev system.

Closes #2097

### CODE REVIEW

**Review by livio-a — COMMENTED** [review]
@peintnermax i'm unsure about the styling (accent color on back button)
image
the rest seems like a simple but good solution

**Comment by hifabienne** [comment]
> @peintnermax i'm unsure about the styling (accent color on back button) image the rest seems like a simple but good solution

I think we normally have the back button in the top left corner next to the logo:
image

**Comment by peintnermax** [comment]
exaclty we should use the `lgn-icon-button` for the back navigation 👍
ex.
```
<a class="lgn-icon-button lgn-left-action" href="{{ }}">
     <i class="lgn-icon-arrow-left-solid"></i>
</a>
```

**Comment by doncicuto** [comment]
Perfect, I'll try to fix It tomorrow. Thanks for your comments and reviews.

**Comment by doncicuto** [comment]
Changes applied as requested. Thanks!

image

**Pull request merged**
