### PR TITLE
chore(console): buf stub build

### PR DESCRIPTION
**Pull request by peintnermax**
```[tasklist]
### Definition of Ready
- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.
```

### CODE REVIEW

**Comment by fforootd** [comment]
@peintnermax since this does work i would recommend proceeding with it and also remove the old code with the grpc.sh and dockerfile. What do you thingk?

**Comment by peintnermax** [comment]
definitely agree on that.. user experience with buf is great IMO👍

**Review by fforootd — APPROVED** [review]
Tested it locally and work well.

@peintnermax can you share your lint settings or check them in?

Seems like they are different than mine

**Comment by peintnermax** [comment]
> Tested it locally and work well.
> 
> @peintnermax can you share your lint settings or check them in?
> 
> Seems like they are different than mine

prettier should do the linting.. you can fix the files with `npm run lint:fix`

**Pull request merged**
