### PR TITLE
docs(search): add getMissingResultsUrl

### LINKED ISSUE #5930: Docs: add getMissingResultsUrl to Algolia search
When a search can't find a result, show a link to the user where to open a discussion for this topic.

```[tasklist]
### Acceptance Criteria
- [ ] Update dependency (bug fix) or docusaurus
- [ ] Add getMissingResultsUrl to config
```

### PR DESCRIPTION
**Pull request by mffap**
Follow-up of https://github.com/zitadel/zitadel/issues/5825

Should return a link to report missing information on the search modal.

https://github.com/algolia/docsearch/releases/tag/v3.3.3

npm outdated results in:  

| Package | Current | Wanted | Latest | Location | Depended by |
| --- | --- | --- | --- | --- | --- | 
| @docsearch/css | 3.0.0 | 3.0.0 | 3.3.5 | node_modules/@docsearch/css | docs | 
| @docsearch/react | 3.0.0 | 3.0.0 | 3.3.5 | node_modules/@docsearch/react | docs |

### CODE REVIEW

**Comment by mffap** [comment]
@peintnermax I've realized that docsearch has an outdated dependency. I wanted to use an attribute but that has been fixed only in a later version introduced around Feb 6. Not sure what's the best way to deal with it? Can we just upgrade the dependency, or should we upgrade also docusaurus? Thanks for the help

**Review by peintnermax — APPROVED** [review]

**Comment by peintnermax** [comment]
> @peintnermax I've realized that docsearch has an outdated dependency. I wanted to use an attribute but that has been fixed only in a later version introduced around Feb 6. Not sure what's the best way to deal with it? Can we just upgrade the dependency, or should we upgrade also docusaurus? Thanks for the help

I'll try to upgrade all deps 👍

**Comment by muhlemmer** [comment]
@mffap, @peintnermax . I'm going over the backlog of approved PRs. Just checking if this is ready to merge? If not, can you please mark is as draft?

**Comment by mffap** [comment]
> @mffap, @peintnermax . I'm going over the backlog of approved PRs. Just checking if this is ready to merge? If not, can you please mark is as draft?

I think there was an issue with the whole plugin. I will close for now. Thanks for the ping.

**Pull request closed without merging**
