### PR TITLE
docs: Create _cloud_postgres.mdx

### PR DESCRIPTION
**Pull request by zoltantemesvari**
# Missing configuration for cloud-based PostgreSQL compatible DB

With this request I intend to complete the documentation for self-hosting Zitadel to be used with cloud PostgreSQL database such as Azure DB for PostgreSQL.

### CODE REVIEW

**Comment by hifabienne** [comment]
hei @zoltantemesvari 
Please make sure the PR title is based on semantic release.
e.g. needs to start with fix: feat: etc.

**Comment by zoltantemesvari** [comment]
> hei @zoltantemesvari Please make sure the PR title is based on semantic release. e.g. needs to start with fix: feat: etc.

Hi, newby question: how do I do that? Like this?

**Comment by hifabienne** [comment]
> > hei @zoltantemesvari Please make sure the PR title is based on semantic release. e.g. needs to start with fix: feat: etc.
> 
> Hi, newby question: how do I do that? Like this?

your change already did that. 😃 its just to mark the beginning of the description with what kind of change it is

**Review by adlerhurst — CHANGES_REQUESTED** [review]
Hi @zoltantemesvari 

Thanks for your contribution. I think it would make sense to add this section as a detail to the postgres configuration (https://docs-git-fork-zoltantemesvari-patch-1-zitadel.vercel.app/docs/self-hosting/manage/database)

I would add it after. [here](https://github.com/zoltantemesvari/zitadel/blob/a28ed5b7bc5d213649efb11d68135e940f7ca115/docs/docs/self-hosting/manage/database/_postgres.mdx?plain=1#L7)

**Comment by hifabienne** [comment]
hei @zoltantemesvari 
Did you see the comment of @adlerhurst ?
Do you still work on this?

**Comment by hifabienne** [comment]
I will close this pr for now, due to inactivity.
@zoltantemesvari please feel free to open a new one once you have addressed the input

**Pull request closed without merging**
