### PR TITLE
chore: api brainstorming

### PR DESCRIPTION
**Pull request by fforootd**
non working WIP

### CODE REVIEW

**Comment by fforootd** [comment]
This is a WIP and I am currently looking into some styling guides. E.g from https://github.com/Redocly/openapi-starter/tree/main/openapi

**Comment by peintnermax** [comment]
@fforootd can we merge this into https://github.com/zitadel/zitadel/pull/4829? 🤔

**Comment by fforootd** [comment]
> @fforootd can we merge this into #4829? 🤔

Yes we can

**Comment by fforootd** [comment]
@peintnermax i resovled some conflicts, should work now

**Pull request merged**
