### PR TITLE
chore(ci): merge test runs

### PR DESCRIPTION
**Pull request by eliobischof**
Replaces #6146 

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Critical parts are tested automatically
- [ ] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

### CODE REVIEW

**Comment by eliobischof** [comment]
@stebenz do you have an idea why TestServer_SAMLACS fails?

**Comment by stebenz** [comment]
> @stebenz do you have an idea why TestServer_SAMLACS fails?

Yes, there was a fix by @livio-a  to correct the behavior of the SAML SP if you configure a specific binding, and as the error states: It should be a redirect but it receives a POST.
I'm surprised that this test didn't fail before, but you only have to change the IDP provider configuration, and then it should work again.

**Comment by eliobischof** [comment]
> > @stebenz do you have an idea why TestServer_SAMLACS fails?
> 
> Yes, there was a fix by @livio-a to correct the behavior of the SAML SP if you configure a specific binding, and as the error states: It should be a redirect but it receives a POST. I'm surprised that this test didn't fail before, but you only have to change the IDP provider configuration, and then it should work again.

I'm not sure what I have to do now. The tests obviously only fail on this branch, not on main. Which fix are you referring to?

**Comment by stebenz** [comment]
@eliobischof Seems like the tests were excluded before due to the list of paths.
I tried to add the bindings to the created providers and will take care of it if it still not works.

**Comment by eliobischof** [comment]
@livio-a thanks for reviewing and updating the branch protection

**Review by livio-a — APPROVED** [review]

**Pull request merged**
