### PR TITLE
fix: fixed broken documentation links

### PR DESCRIPTION
**Pull request by dol**
I found some broken links in the UI to the moved documentation.

I used https://github.com/lycheeverse/lychee to scan for broken links.

```
$ cat <<'EOF' > .lycheeignore
^file://
^https://accounts\.exmaple\.com/saml/metadata$
^https://demo\.com/tos-%7B%7B.Lang%7D%7D$
^https://example\.auth0\.com/samlp/metadata\?connection=SAML-ZITADEL$
^https://gitlab\.com/dashboard/groups$%
EOF
$ lychee --verbose --no-progress --exclude-link-local --exclude-mail --exclude-loopback .
```

### CODE REVIEW

**Review by fforootd — DISMISSED** [review]
Thank you for the PR!

It looks like we missed those while reworking the docs :grin:

**Comment by fforootd** [comment]
@hifabienne I think we should keep this named as fix since it fixes broken links in `console`

**Comment by fforootd** [comment]
@dol can you run [prettier](https://github.com/zitadel/zitadel/blob/main/console/package.json#L10) on your fork. It looks like the angular lint is [unheapy](https://github.com/zitadel/zitadel/actions/runs/3125371190/jobs/5074838299#step:7:87)

**Comment by dol** [comment]
@fforootd I'll do.

image

**Comment by fforootd** [comment]
> @fforootd I'll do.
> 
> image

:grin: `npm run lint:fix`

**Review by fforootd — APPROVED** [review]

**Pull request merged**
